# Generated by Django 5.1.3 on 2024-11-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_postlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
