# Generated by Django 5.1.3 on 2024-11-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='like',
        ),
    ]
