# Generated by Django 5.1.3 on 2024-11-12 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=255)),
                ('code', models.CharField(max_length=8, null=True)),
                ('members', models.ManyToManyField(related_name='members', to='api.account')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='group', to='api.account')),
            ],
        ),
    ]
