# Generated by Django 5.1.3 on 2024-11-12 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_group_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Private',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
                ('members', models.ManyToManyField(blank=True, related_name='private_members', to='api.account')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='private_group', to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
                ('members', models.ManyToManyField(blank=True, related_name='public_members', to='api.account')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='public_group', to='api.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
