# Generated by Django 5.1.3 on 2024-11-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_private_public_delete_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='code',
        ),
    ]
