# Generated by Django 5.1.3 on 2024-11-13 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_public_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='private',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private', to='api.post'),
        ),
    ]
