# Generated by Django 5.1.3 on 2024-11-13 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_private_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private', to='api.private'),
        ),
    ]
