# Generated by Django 5.1.3 on 2024-11-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_private_post_post_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='private',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.private'),
        ),
    ]
