# Generated by Django 5.1.3 on 2024-11-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_post_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_group', to='api.account'),
        ),
    ]
