# Generated by Django 5.1.3 on 2024-11-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_privateg_alter_post_private_delete_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
